# =========================
# GENERAL SETTINGS
# =========================

output_folder=/var/log/xfcodecs
cgnat_file_path=/etc/xfcodecs/cgnat.rules
interface_name=dummy0
threads=4
extract_all=true

caplen=3200
update_timeout=900
bye_timeout=43200
ring_buffer_size=1048576

# =========================
# INPUT FILES
# =========================

# input_file=/data/capture1.pcap

# =========================
# MYSQL CONFIG
# =========================

mysql_host=127.0.10.1
mysql_database=MDF2
mysql_user=root1
mysql_password=secret1234
mysql_port=3306